import { GoogleGenAI } from '@google/genai';

export class GeminiReviewService {
  private ai: GoogleGenAI;
  private modelName: string;

  constructor(apiKey?: string, modelName: string = 'gemini-2.5-flash') {
    this.ai = apiKey ? new GoogleGenAI({ apiKey }) : new GoogleGenAI({});
    this.modelName = modelName;
  }

  async reviewTestDiff(prTitle: string, prBody: string, diff: string): Promise<string> {
    const systemInstruction = `
You are an expert Principal Automation Quality Architect specializing in Playwright and TypeScript framework design. 
Your job is to review pull requests containing automated test scripts. 
Evaluate the changes for:
1. **Locator Best Practices:** Flag brittle CSS/XPath selectors and ensure resilience by recommending semantic locators (e.g., getByRole, getByText, getByTestId).
2. **Asynchronous Handling:** Ensure all Playwright actions and assertions properly utilize 'await' to prevent race conditions and flakiness.
3. **Assertion Rigor:** Check that test assertions are explicit, meaningful, and validate user-facing outcomes rather than implementation details.
4. **Code Structure & Maintainability:** Check for clean Page Object Model (POM) alignment, hardcoded configuration values, missing cleanups, or readability concerns.

Provide a structured, constructive, and actionable review report in Markdown format. Categorize findings into 'Critical Issues', 'Warnings & Recommendations', and 'Positive Highlights'.
`;

    const prompt = `
### Pull Request Title: ${prTitle}
### Pull Request Description / JIRA Context: ${prBody}

### Code Diff to Review:
\`\`\`diff
${diff}
\`\`\`
`;

    try {
      const response = await this.ai.models.generateContent({
        model: this.modelName,
        contents: prompt,
        config: {
          systemInstruction: systemInstruction,
        },
      });

      return response.text || 'No review feedback generated by the AI.';
    } catch (error) {
      console.error('Error generating review from Gemini API:', error);
      throw error;
    }
  }
}